### PR TITLE
Handle Timeout or server crash during fetching of multiple pages of records

### PR DESCRIPTION
**Pull request by MoralCode**
this is the beginnings of a fix for #58. So far I have only restructured the error checking to add an else block where this issue can be handled, but haven't yet gotten to figuring out how to actually start fetching over from the beginning as suggested by the Airtable docs

### CODE REVIEW

**Comment by MoralCode** [comment]
Thinking maybe a good way to do this might be to throw a specific kind of error and catch it at the point where `select` is called and implement the retry logic there.

**Comment by GV14982** [comment]
Hey there, I'm going to close this for now, as it seems to have caught up my github actions.

**Comment by GV14982** [comment]
> > Hey there, I'm going to close this for now, as it seems to have caught up my github actions.
> 
> what do you mean "caught up my github actions"? like was this PR breaking the existing workflows?

Ooops sorry for the late reply.

Yeah it had got the github actions stuck in a state where it wouldn't allow me to restart these, and it wouldn't start any new ones.

Let me know if you end up doing any more work on this and I'll be happy to re-open.

**Comment by MoralCode** [comment]
That seems weird. Do you think i would be able to recreate the problem in a fork of this repo using the same github actions? Are they Github actions that were added to the main branch since i made this PR?

I can probably play with it to see if i can get it working (maybe rebasing to the lastest main branch would help?), but other than that, as far as i remember this fix was "done". Is there anything you feel needs work on before it can get merged?

**Comment by GV14982** [comment]
Ah I didn't realize it was done already. So two things:
1. Maybe try rebasing from develop
2. Make sure to change the target for this PR to develop. Our branching strategy is: branch -> develop -> main

The develop branch equates to the @next tag in NPM.

**Pull request closed without merging**
